name: Build & Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-mac-silicon:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system deps
        run: brew install cmake

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Mac .dmg
        working-directory: rs
        env:
          MACOSX_DEPLOYMENT_TARGET: "11.0"
          CFLAGS: "-mmacosx-version-min=11.0"
          CXXFLAGS: "-mmacosx-version-min=11.0"
        run: cargo tauri build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Typeoff-Mac-AppleSilicon
          path: rs/target/release/bundle/dmg/*.dmg
